"""create_versioned_ml_tables

Revision ID: f0323fa06b8d
Revises: 
Create Date: 2026-07-17 13:09:02.244311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0323fa06b8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_ai_extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('extraction_data', sa.JSON(), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_blocks', sa.JSON(), nullable=True),
    sa.Column('page_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=False),
    sa.Column('processing_pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('source_application', sa.String(length=100), server_default='invoice-ocr-platform', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_ai_created', 'raw_ai_extractions', ['created_at'], unique=False)
    op.create_index('idx_raw_ai_doc_ver', 'raw_ai_extractions', ['document_id', 'version'], unique=False)
    op.create_index('idx_raw_ai_model', 'raw_ai_extractions', ['model_name', 'model_version'], unique=False)
    op.create_index(op.f('ix_raw_ai_extractions_created_at'), 'raw_ai_extractions', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_ai_extractions_is_deleted'), 'raw_ai_extractions', ['is_deleted'], unique=False)
    op.create_table('user_verified_extractions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('verified_data', sa.JSON(), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=False),
    sa.Column('reviewer_role', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('training_status', sa.String(length=30), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('was_corrected', sa.Boolean(), nullable=False),
    sa.Column('number_of_fields_changed', sa.Integer(), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('edit_distance_score', sa.Float(), nullable=False),
    sa.Column('field_accuracy', sa.Float(), nullable=False),
    sa.Column('overall_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('source_application', sa.String(length=100), server_default='invoice-ocr-platform', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_ver_created', 'user_verified_extractions', ['created_at'], unique=False)
    op.create_index('idx_user_ver_doc_ver', 'user_verified_extractions', ['document_id', 'version'], unique=False)
    op.create_index('idx_user_ver_reviewer', 'user_verified_extractions', ['verified_by'], unique=False)
    op.create_index('idx_user_ver_status', 'user_verified_extractions', ['training_status'], unique=False)
    op.create_index(op.f('ix_user_verified_extractions_created_at'), 'user_verified_extractions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_verified_extractions_is_deleted'), 'user_verified_extractions', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verified_extractions_is_deleted'), table_name='user_verified_extractions')
    op.drop_index(op.f('ix_user_verified_extractions_created_at'), table_name='user_verified_extractions')
    op.drop_index('idx_user_ver_status', table_name='user_verified_extractions')
    op.drop_index('idx_user_ver_reviewer', table_name='user_verified_extractions')
    op.drop_index('idx_user_ver_doc_ver', table_name='user_verified_extractions')
    op.drop_index('idx_user_ver_created', table_name='user_verified_extractions')
    op.drop_table('user_verified_extractions')
    op.drop_index(op.f('ix_raw_ai_extractions_is_deleted'), table_name='raw_ai_extractions')
    op.drop_index(op.f('ix_raw_ai_extractions_created_at'), table_name='raw_ai_extractions')
    op.drop_index('idx_raw_ai_model', table_name='raw_ai_extractions')
    op.drop_index('idx_raw_ai_doc_ver', table_name='raw_ai_extractions')
    op.drop_index('idx_raw_ai_created', table_name='raw_ai_extractions')
    op.drop_table('raw_ai_extractions')
    # ### end Alembic commands ###
